### ISSUE TITLE
Add progress bar to launcher when installing

### ISSUE THREAD

**Issue by dilirity** [gb2dev/HLA-NoVR-Launcher#11]
It says downloading, but I can't be sure that it isn't stuck. Network is at 0mbps.

**Comment by TarekLP** [comment]
It doesnt need an internet connection once its downloaded, and the files are only like 20mb

**Comment by dilirity** [comment]
So I guess it's okay for this to look like it's stuck?

**Comment by gb2dev** [comment]
that's a GitHub serverside issue
