### ISSUE TITLE
Cant find folder to set up NoVR launcher (Installation not found)

### ISSUE THREAD

**Issue by Tibbles09** [gb2dev/HLA-NoVR-Launcher#33]
I've installed the launcher but it will not find the right folder to set up the mod. I've done every folder and it just says HLA installation not found. I see the hidden files on the steam folder but now when I try and set it up via the launcher.

**Comment by gb2dev** [comment]
Read this: https://github.com/gb2dev/HLA-NoVR-Launcher?tab=readme-ov-file#important-information

If it still says installation not found something is wrong with your game installation or you still selected the wrong folder. The launcher just checks if the game's exe us at the right path.

**Comment by gb2dev** [comment]
You're using the Windows launcher, of course it won't work. You have to use the Linux/Steam Deck version (the launcher is outdated though, so you probably need to do the installation manually)

**Comment by TarekLP** [comment]
where are you running it from?
