### ISSUE TITLE
choppy performance

### ISSUE THREAD

**Issue by popalazarou** [gb2dev/HLA-NoVR-Launcher#36]
this mod worked fine for me before and i played a fair amount of the game.  If i am honest i think i was using a different version of the no vr mod before.  After this latest more complete version i seem to have really choppy gameplay.  The fps is mostly around 100 but drops erratically here and there.  Sometimes it runs perfectly , but rarely.  I dont know what happened but originally i was getting 120fps flat out al, the time, now it drops to 80 and 60, but even if i set the fps in rtss to 60 its still really choppy.  (i dont think its an fps issue)I dont know what to try next.  I tried another version of the vr mod but it doesnt allow me to select anything.  I would like to use this version as it seems to be the most complete.  hope you can help thanks. 

latest drivers w10
rtx2060 oc
i78700k  oc
16gb
ssd

**Comment by TarekLP** [comment]
you will need to set your graphics settings down, and close any running programs in teh background
also disabling hardware acceleration in discord can help

**Comment by popalazarou** [comment]
ok thankyou :)
i have it running nicely now

one thing i have noticed is it seems to crash shortly after loading (sometimes).  Also when i go to play the game sometimes the buttons dont allow me to "continue" or  "load" "savegame".  Its weird because it doesnt do it everytime.  Sometimes i will wait till the next day and try the game again like to today and it allows me to continue.  I completed a few levels and then as i am say 3 levels in the game crashes .  it just feels a lot buggier than when i first used the no vr mod.  The only thing i can think of is to place it on my ssd at some point maybe that may make it more stable.  Appreciate all you efforts :)
