### ISSUE TITLE
Launcher is stuck and game ignores the launch params and starts in vr mode

### ISSUE THREAD

**Issue by Sprosenax** [gb2dev/HLA-NoVR-Launcher#41]
It stays like this forever and doesnt do anything :/ 
edit: i tried with my headset unplugged and started the launcher as admin still nothing

![image](https://github.com/user-attachments/assets/0a372f33-f1f4-4824-9d84-f276bb59d9fc)

**Comment by gb2dev** [comment]
What does Steam show after you click play and how does the game window look like. I'd appreciate more screenshots or a recording

**Comment by Sprosenax** [comment]
> What does Steam show after you click play and how does the game window look like. I'd appreciate more screenshots or a recording

Steam doesn't show anything after i hit play, game starts as usual and ignoring the launch params (i guess)

**Comment by gb2dev** [comment]
This doesn't help me

**Comment by Sprosenax** [comment]
> This doesn't help me, you already said this

alright i verified the game files for the second time and now it worked but main menu buttons not showing up :/ i can start the game from vconsole atleast

**Comment by gb2dev** [comment]
Check the "Force mod reinstall" option in the launcher and try again (because verifying probably uninstalled the mod)

**Comment by Sprosenax** [comment]
> Check the "Force mod reinstall" option in the launcher and try again (because verifying probably uninstalled the mod)

everything works now, thanks.
