### ISSUE TITLE
README was deleted

### ISSUE THREAD

**Issue by bart-blommaerts** [gb2dev/HLA-NoVR-Launcher#42]
In this commit; https://github.com/gb2dev/HLA-NoVR-Launcher/commit/0f3c1ffb0e52c6310f92357d153c4a75ebcbada3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Will likey make it more difficult for people to install.

**Comment by gb2dev** [comment]
Fixed
