### ISSUE TITLE
Rebinding Movement keys (to arrow keys) not working.

### ISSUE THREAD

**Issue by gibxxi** [gb2dev/HLA-NoVR-Launcher#43]
As the title suggests, I am unable to rebind the movement keys to arrow keys (I cannot play FPS games with WASD, Always used arrow keys).

While the binding in the NoVR mod is successful, it has no effect in-game. The arrow keys still perform the 'look up', 'look down', 'look left', 'look right' actions, and WASD is still being used for movement. As a work-around I've had to swap the key bindings manually in the main game's  'user_keys_default.vcfg' file to be able to play the game using this mod.

Other key bindings changed in the mod (jump, run, etc.) were successful and work without issue.

**Comment by Lambda321** [comment]
Same here and nothing changes. New releases just ADD more bugs not fixing old Ones

**Comment by kborowinski** [comment]
Same here. The arrow keys are not working.

**Comment by gb2dev** [comment]
Thank you for looking up all the corresponding key names for Godot, fixing this will be very easy now

**Comment by kborowinski** [comment]
@gb2dev Here you have link to the Valve developer community with all the key names:
[https://developer.valvesoftware.com/wiki/Bind](https://developer.valvesoftware.com/wiki/Bind)

**Comment by gibxxi** [comment]
@gb2dev Thank you for fixing / addressing this issue, much appreciated.

:o)

**Comment by gibxxi** [comment]
Thorough investigative work there @kborowinski, good catch. ;o)
