### ISSUE TITLE
Main menu buttons don't respond when clicked

### ISSUE THREAD

**Issue by miscohen** [gb2dev/HLA-NoVR-Launcher#45]
After updating HLA-NoVR-Launcher to 4.2 the main menu buttons stop responding when clicked.
When going back to 4.1 the main menu buttons works perfectly fine.
(Can I disable auto-update somehow at the meantime so I can stay in ver. 4.1?)

**Comment by DarkEviL88** [comment]
Same issue

**Comment by wgoff194** [comment]
Same issue on 4.2

**Comment by gb2dev** [comment]
Fixed, was caused by https://github.com/godotengine/godot/issues/100097
