### ISSUE TITLE
Latest update 4.2 makes game unplayable

### ISSUE THREAD

**Issue by Lambda321** [gb2dev/HLA-NoVR-Launcher#46]
Same here
After updating or Bretter said downgrading? To laucher 4.2 - the main  menu either not appear at all, or if you press m it appears but not works. nothing happens when you press something.
Old issue still not fixed with key bindings- you change bindings- in menu but in the game it not changes. Cant assign arrows or mouse 3 4 etc.
And last not least. You made installer right? But please make uninstaller too!

**Comment by gb2dev** [comment]
#45
